version: "3.8"

services:
  postgres:
    image: 'postgres:15.7-alpine'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'
    ports:
      - '46661:5432'
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379'
