spring:
  config:
    activate:
      on-profile: local
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      client-type: lettuce
      password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 500
      thread-name-prefix: implace-async-