spring:
  config:
    activate:
      on-profile: mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: im.support@implace.kr
    password: dfsjkceftzwfmlkq
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true