name: ssl-update

#on:
#  schedule:
#    - cron: '00 12 1 * *'
#  workflow_dispatch:
on:
  push:
    branches:
      - feature/lchy/ssl

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            sudo systemctl stop nginx
            sudo certbot renew
            sudo systemctl start nginx